resources:
- name: springboot_starter
  type: git
  source:
    branch: master
    uri: https://github.com/Tegegn/springboot_starter.git
  check_every: 60s  

jobs:
- name: Auto-run
  plan:
  - get: springboot_starter
    trigger: true
  - task: do-your-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "This job is automatically triggered upon any version change in the resource."
- name: Manually-trigger
  plan:
  - get: springboot_starter
    passed: [Auto-run]
    trigger: false
  - task: do-your-manual-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of your manually triggered task."
- name: Do-more-stuff
  plan:
  - get: springboot_starter
    passed: [Manually-trigger]
    trigger: true
  - task: do-other-tasks-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of your other tasks."