resources:
- name: springboot_starter
  type: git
  source:
    branch: master
    uri: https://github.com/Tegegn/springboot_starter.git
  check_every: 60s   
   
jobs:
- name: Run-automatically
  plan:
  - get: springboot_starter
    trigger: true
  - task: do-your-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "This job is automatically triggered upon any version change in the resource."
- name: Manually-trigger-me
  plan:
  - get: springboot_starter
    passed:
      - Run-automatically
    trigger: false
  - task: do-your-manual-task-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of your manually triggered task."
- name: Do-more-stuff-after-manual-trigger
  plan:
  - get: springboot_starter
    passed:
      - Manually-trigger-me
    trigger: true
  - task: do-other-tasks-here
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: sh
        args:
        - -exc
        - |
          echo "Output of your other tasks."